package rishark.pcap.frame.link.network.protocols.ipv4.transport.application.protocols.dhcp;

public enum DHCPOptionsCode {

    SUBNET_MASK(1), // o a
    TIME_OFFSET(2),
    ROUTER(3),
    TIME_SERVER(4),
    NAME_SERVER(5),
    DNS_IP(6),
    LOG_SERVER(7),
    QUOTE_SERVER(8),
    LPR_SERVER(9),
    IMPRESS_SERVER(10),
    RESOURCE_LOCATION_SERVER(11),
    HOST_NAME(12),
    BOOT_FILE_SIZE(13),
    MERIT_DUMP_FILE(14),
    DOMAIN_NAME(15),
    SWAP_SERVER(16),
    ROOT_PATH(17),
    EXTENSIONS_PATH(18),
    IP_FORWARDING_ENABLE_DISABLE(19),
    NON_LOCAL_SOURCE_ROUTING_ENABLE_DISABLE(20),
    POLICY_FILTER(21),
    MAXIMUM_DATAGRAM_REASSEMBLY_SIZE(22),
    DEFAULT_IP_TTL(23),
    PATH_MTU_AGING_TIMEOUT(24),
    PATH_MTU_PLATEAU_TABLE(25),
    MTU_INTERFACE(26),
    ALL_SUBNETS_LOCAL(27),
    BROADCAST_ADDRESS(28),
    PERFORM_MASK_DISCOVERY(29),
    MASK_SUPPLIER(30),
    PERFORM_ROUTER_DISCOVERY(31),
    ROUTER_SOLICITATION_ADDRESS(32),
    STATIC_ROUTE(33),
    TRAILER_ENCAPSULATION(34),
    ARP_CACHE_TIMEOUT(35),
    ETHERNET_ENCAPSULATION(36),
    DEFAULT_TCP_TTL(37),
    TCP_KEEPALIVE_INTERVAL(38),
    TCP_KEEPALIVE_GARBAGE(39),
    NETWORK_INFORMATION_SERVICE_DOMAIN(40),
    NETWORK_INFORMATION_SERVICE_SERVERS(41),
    NTP_SERVER(42),
    VENDOR_SPECIFIC_INFO(43),
    NETBIOS_NS(44),
    NETBIOS_DATAGRAM_DISTRIBUTION_SERVER(45),
    NETBIOS_NODE_TYPE(46),
    NETBIOS_SCOPE(47),
    X_WINDOW_SYSTEM_FONT_SERVER(48),
    X_WINDOW_SYSTEM_DISPLAY_MANAGER(49),
    REQUESTED_IP_ADDRESS(50), // d r
    IP_ADDRESS_LEASE_TIME(51), // o a
    OPTION_OVERLOAD(52),
    DHCP_MESSAGE_TYPE(53), // d o r a
    DHCP_SERVER_IDENTIFIER(54), // o r a
    PARAMETER_REQUEST_LIST(55), // d r
    MESSAGE(56),
    MAXIMUM_DHCP_MESSAGE_SIZE(57),
    RENEWAL_TIME_VALUE(58), // o a
    REBINDING_TIME_VALUE(59), // o a
    VENDOR_CLASS_IDENTIFIER(60),
    CLIENT_IDENTIFIER(61), // d r
    NETWARE_DOMAIN_NAME(62),
    NETWARE_IP_INFORMOATION(63),
    NETWORK_INFORMATION_SVC_DOMAIN(64),
    NETWORK_INFORMATION_SVC_SERVERS(65),
    TFTP_SERVER_NAME(66),
    BOOT_FILE_NAME(67),
    MOBILE_IP_HOME_AGENT(68),
    SIMPLE_MAIL_TRANSPORT_PROTOCOL_SERVER(69),
    POST_OFFICE_PROTOCOL_SERVER(70),
    NETWORK_NEWS_TRANSPORT_PROTOCOL_SERVER(71),
    DEFAULT_WORLD_WIDE_WEB_SERVER(72),
    DEFAULT_FINGER_SERVER(73),
    DEFAULT_INTERNET_RELAY_CHAT_SERVER(74),
    STREETTALK_SERVER(75),
    STREETTALK_DIRECTORY_ASSISTANCE_SERVER(76),
    USER_CLASS_INFORMATION(77),
    SLP_DIRECTORY_SCOPE(78),
    SLP_SERVICE_SCOPE(79),
    RAPID_COMMIT(80),
    FQDN(81),
    RRELAY_AGENT_INFORMATION(82),
    INTERNET_STORAGE_NS(83),

    NDS_SERVERS(85),
    NDS_TREE_NAME(86),
    NDS_CONTEXT(87),
    BCMCS_NAME_LIST(88),
    BCMCS_IP_LIST(89),
    AUTHENTICATION(90),
    CLIENT_LAST_TRANSACTION_TIME(91),
    ASSOCIATED_IP(92),
    CLIENT_SYSTEM_ARCHITECURE_TYPE(93),
    CLIENT_NETWORK_INTERFACE_IDENTIFIER(94),
    LDAP(95),

    CLIENT_MACHINE_IDENTIFIER(97),
    OPEN_GROUP_USER_AUTHENTICATION(98),
    GEOCONF_CIVIC(99),
    IEEE_1003_1_STRING(100),
    REFERENCE_TZ_DATABASE(101),

    NETINFO_PARENT_SERVER_ADDRESS(112),
    NETINFO_PARENT_SERVER_TAG(113),
    URL(114),

    AUTOCONFIGURE(116),
    NAME_SERVICE_SEARCH(117),
    SUBNET_SELECTION(118),
    DNS_SEARCH_LIST(119),
    SIP_SERVERS_DHCP_OPTIONS(120),
    CLASSLESS_STATIC_ROUTE(121),
    CCC(122),
    GEOCONF(123),
    VENDOR_IDENTIFYING_VENDOR_CLASS(124),
    VENDOR_IDENTIFYING_VENDOR_SPECIFIC(125),


    TFTP_SERVER_IP_ADDRESS(128),
    CALL_SERVER_IP_ADDRESS(129),
    DISCRIMINATION_STRING(130),
    REMOTE_STATISTICS_SERVER_IP_ADDRESS(131),
    _802_1_VLAN_ID(132),
    _802_PRIORITY(133),
    DIFFSERVER_CODE_POINT(134),
    HTTP_PROXY_PHONE(135),
    PANA_AUTH_AGENT(136),
    LOST_SERVER(137),
    CAPWAP(138),
    OPT_IPV4_ADDRESS_MOS(139),
    OPT_IPV4_FQDN_MOS(140),
    SIP_UA_CONF_SERVICE_DOMAIN(141),
    OPT_IPV4_ADDRESS_ANDSF(142),
    OPY_IPV6_ADDRESS_ANDSF(143),

    TFTP_SERVER_ADDRESS(150),
    STATUS_CODE(151),
    BASE_TIME(152),
    START_TIME_STATE(153),
    QUERY_START_TIME(154),
    QUERY_END_TIME(155),
    DHCP_STATE(156),
    DATA_SOURCE(157),

    ETHERBOOT(175),
    IP_PHONE(176),
    ETHERBOOT_PACKETCABLE(177),

    PRELINUX_MAGIC(208),
    PRELINUX_CONFIGFILE(209),
    PRELINUX_PATHPREFIX(210),
    PRELINUX_REBOOT_TIME(211),
    OPTION_6RD(212),
    OPTION_V4_ACCESS_DOMAIN(213),

    SUBNET_ALLOCATION(220),
    VIRTUAL_SUBNET_SELECTION(221),

    PRIVATE_STATIC_ROUTE(249),
    PRIVATE_AUTODISCOVERY(252),
    END(255); // d o r a

    private final int dhcpOptionsCode;

    DHCPOptionsCode(int dhcpOptionsCode) {
        this.dhcpOptionsCode = dhcpOptionsCode;
    }

    public static DHCPOptionsCode findDhcpOptionsCode(int i){
        for(DHCPOptionsCode oc : DHCPOptionsCode.values()) {
            if(oc.getDhcpOptionsCode() == i) {
                return oc;
            }
        }
        return null;
    }

    public int getDhcpOptionsCode() {
        return dhcpOptionsCode;
    }
}
